CREATE TABLE IF NOT EXISTS CATALOGO_MUSICA 
(   ID_CATALOGO_MUSICA         INTEGER         PRIMARY KEY AUTOINCREMENT NOT NULL
    ,NOMBRE             VARCHAR(30)     NOT NULL
    ,OBSERVACION        VARCHAR(100)    DEFAULT('')
    ,FECHA_CREACION     VARCHAR(20)     DEFAULT(datetime('now'))
    ,FECHA_MODIFICA     VARCHAR(20)     DEFAULT(datetime('now'))
    ,ESTADO             VARCHAR(1)      DEFAULT('En Stock')
);
------------------------------------------------------------------
INSERT INTO CATALOGO_MUSICA (NOMBRE)
        VALUES ('POP');
INSERT INTO CATALOGO_MUSICA (NOMBRE)
        VALUES ('ROCK');
INSERT INTO CATALOGO_MUSICA (NOMBRE)
        VALUES ('EMO');
INSERT INTO CATALOGO_MUSICA (NOMBRE)
        VALUES ('REGUETON');
INSERT INTO CATALOGO_MUSICA (NOMBRE)
        VALUES ('RAP');
-------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS CANTANTE 
(   ID_CANTANTE             INTEGER         PRIMARY KEY AUTOINCREMENT  
    ,ID_CATALOGO_MUSICA        INTEGER         NOT NULL
    ,NOMBRE             VARCHAR(30)     NOT NULL
    ,OBSERVACION        VARCHAR(100)    DEFAULT('')
    ,FECHA_CREACION     VARCHAR(20)     DEFAULT(datetime('now'))
    ,FECHA_MODIFICA     VARCHAR(20)     DEFAULT(datetime('now'))
    ,ESTADO             VARCHAR(1)      DEFAULT('En Stock')
    ,CONSTRAINT FK_ID_CATALOGO_MUSICA
    FOREIGN KEY (ID_CATALOGO_MUSICA) REFERENCES CATALOGO_MUSICA (ID_CATALOGO_MUSICA)
);
------------------------------------------------------------------
INSERT INTO CANTANTE (ID_CATALOGO_MUSICA, NOMBRE)
        VALUES (1, 'TAYLOR SWIFT');
INSERT INTO CANTANTE (ID_CATALOGO_MUSICA, NOMBRE)
        VALUES (1, 'OLIVIA RODRIGO');
INSERT INTO CANTANTE (ID_CATALOGO_MUSICA, NOMBRE)
        VALUES (2, 'QUEEN');
INSERT INTO CANTANTE (ID_CATALOGO_MUSICA, NOMBRE)
        VALUES (2, 'LINKIN PARK');
INSERT INTO CANTANTE (ID_CATALOGO_MUSICA, NOMBRE)
        VALUES (3, 'MY CHEMECAL ROMANCE');
INSERT INTO CANTANTE (ID_CATALOGO_MUSICA, NOMBRE)
        VALUES (3, 'GREEEN DAY');
INSERT INTO CANTANTE (ID_CATALOGO_MUSICA, NOMBRE)
        VALUES (4, 'KAROL G');
INSERT INTO CANTANTE (ID_CATALOGO_MUSICA, NOMBRE)
        VALUES (4, 'BAD BUNNY');
INSERT INTO CANTANTE (ID_CATALOGO_MUSICA, NOMBRE)
        VALUES (5, 'DOJA CAT');
INSERT INTO CANTANTE (ID_CATALOGO_MUSICA, NOMBRE)
        VALUES (5, 'TRAVIS SCOTT');
------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS CANCION 
(   ID_CANCION      INTEGER         PRIMARY KEY AUTOINCREMENT
    ,ID_CANTANTE            INTEGER         NOT NULL
    ,ID_CATALOGO_MUSICA        INTEGER         NOT NULL
    ,NOMBRE             VARCHAR(30)     NOT NULL
    ,OBSERVACION        VARCHAR(100)    DEFAULT('')
    ,FECHA_CREACION     VARCHAR(20)     DEFAULT(datetime('now'))
    ,FECHA_MODIFICA     VARCHAR(20)     DEFAULT(datetime('now'))
    ,ESTADO             VARCHAR(1)      DEFAULT('En Stock')
    ,CONSTRAINT FK_ID_CANTANTE
    FOREIGN KEY (ID_CANTANTE) REFERENCES CANTANTE (ID_CANTANTE)
    ,CONSTRAINT FK_ID_CATALOGO_MUSICA
    FOREIGN KEY (ID_CATALOGO_MUSICA) REFERENCES CATALOGO_MUSICA (ID_CATALOGO_MUSICA)

);
-------------------------------------------------------------------
INSERT INTO CANCION (ID_CATALOGO_MUSICA, ID_CANTANTE, NOMBRE)
        VALUES (1, 1, 'BLANCK SPACE');
INSERT INTO CANCION (ID_CATALOGO_MUSICA, ID_CANTANTE, NOMBRE)
        VALUES (1, 2, 'VAMPIRE');
INSERT INTO CANCION (ID_CATALOGO_MUSICA, ID_CANTANTE, NOMBRE)
        VALUES (2, 3, 'SOMEBODY TO LOVE');
INSERT INTO CANCION (ID_CATALOGO_MUSICA, ID_CANTANTE, NOMBRE)
        VALUES (2, 4, 'IN THE END');
INSERT INTO CANCION (ID_CATALOGO_MUSICA, ID_CANTANTE, NOMBRE)
        VALUES (3, 5, 'WELCOME TO THE BLACK PARADE');
INSERT INTO CANCION (ID_CATALOGO_MUSICA, ID_CANTANTE, NOMBRE)
        VALUES (3, 6, 'WAKE ME UP WHEN SEPTEMBER ENDS');
INSERT INTO CANCION (ID_CATALOGO_MUSICA, ID_CANTANTE, NOMBRE)
        VALUES (4, 7, 'GATUBELA');
INSERT INTO CANCION (ID_CATALOGO_MUSICA, ID_CANTANTE, NOMBRE)
        VALUES (4, 8, 'QUE MALO');
INSERT INTO CANCION (ID_CATALOGO_MUSICA, ID_CANTANTE, NOMBRE)
        VALUES (5, 9, 'DEMONS');
INSERT INTO CANCION (ID_CATALOGO_MUSICA, ID_CANTANTE, NOMBRE)
        VALUES (5, 10, 'SICKOMODE');
SELECT * FROM CANCION

------------------------------------------------------------

